version: '3'

services:
  app:
    build: .
    platform: linux/amd64
    volumes:
      - ./household_app/app/:/home/local/
      - node_modules:/home/local/node_modules
    stdin_open: true
    tty: true
    ports:
      - 8081:8081
    command: >
      sh -c "yarn start"

volumes:
  node_modules:
